/*
 * gen_tables - build-time generator for hebcal-c year-type lookup tables.
 *
 * Produces tables_data.h containing precomputed static-const arrays that
 * replace Go's runtime init() in hdate/tables.go.  The output uses PROGMEM
 * so the tables live in flash on AVR (no-op on desktop/ESP32).
 *
 * Build & run:
 *   cc -o tools/gen_tables tools/gen_tables.c && ./tools/gen_tables > src/tables_data.h
 *
 * License: GPL-2.0-or-later
 */
#include <stdio.h>

#define NUM_YEAR_TYPES 6
#define MAX_DAYS_IN_YEAR 385
#define NISAN   1
#define IYYAR   2
#define SIVAN   3
#define TAMUZ   4
#define AV      5
#define ELUL    6
#define TISHREI 7
#define CHESHVAN 8
#define KISLEV  9
#define TEVET   10
#define SHVAT   11
#define ADAR1   12
#define ADAR2   13

static int year_len_of_type(int t) {
    return 353 + t % 3 + 30 * (t / 3);
}

static int days_in_month_tab[NUM_YEAR_TYPES][ADAR2 + 1];
static int month_offset_tab[NUM_YEAR_TYPES][ADAR2 + 2];
static int month_by_day_of_year[NUM_YEAR_TYPES][MAX_DAYS_IN_YEAR];

static int days_in_month(int t, int m) {
    if (m < NISAN || m > ADAR2) return 30;
    return days_in_month_tab[t][m];
}

int main(void) {
    for (int t = 0; t < NUM_YEAR_TYPES; t++) {
        int yearLen = year_len_of_type(t);
        int leap = yearLen > 355;
        int longCheshvan = yearLen % 10 == 5;
        int shortKislev = yearLen % 10 == 3;

        for (int m = NISAN; m <= ADAR2; m++) {
            int days = 30;
            switch (m) {
            case IYYAR: case TAMUZ: case ELUL: case TEVET: case ADAR2:
                days = 29; break;
            case ADAR1:
                if (!leap) days = 29; break;
            case CHESHVAN:
                if (!longCheshvan) days = 29; break;
            case KISLEV:
                if (shortKislev) days = 29; break;
            }
            days_in_month_tab[t][m] = days;
        }

        int lastMonth = leap ? ADAR2 : ADAR1;

        for (int m = 0; m <= ADAR2 + 1; m++) {
            int offset = 0;
            if (m < TISHREI) {
                for (int x = TISHREI; x <= lastMonth; x++)
                    offset += days_in_month(t, x);
                for (int x = NISAN; x < m; x++)
                    offset += days_in_month(t, x);
            } else {
                for (int x = TISHREI; x < m; x++)
                    offset += days_in_month(t, x);
            }
            month_offset_tab[t][m] = offset;
        }

        /* fill month_by_day_of_year */
        for (int m = 0; m < MAX_DAYS_IN_YEAR; m++)
            month_by_day_of_year[t][m] = 0;
        for (int m = TISHREI; m <= lastMonth; m++) {
            int off = month_offset_tab[t][m];
            for (int i = 0; i < days_in_month(t, m); i++)
                month_by_day_of_year[t][off + i] = m;
        }
        for (int m = NISAN; m <= ELUL; m++) {
            int off = month_offset_tab[t][m];
            for (int i = 0; i < days_in_month(t, m); i++)
                month_by_day_of_year[t][off + i] = m;
        }
    }

    /* Emit header */
    printf("/* AUTO-GENERATED by tools/gen_tables.c - DO NOT EDIT. */\n");
    printf("#ifndef TABLES_DATA_H\n#define TABLES_DATA_H\n\n");
    printf("#include \"arduino_compat.h\"\n\n");
    printf("#include <stdint.h>\n\n");
    printf("#define HEB_NUM_YEAR_TYPES %d\n", NUM_YEAR_TYPES);
    printf("#define HEB_MAX_DAYS_IN_YEAR %d\n\n", MAX_DAYS_IN_YEAR);

    printf("/* days_in_month_tab[t][m]: days in Hebrew month m (1-13) for year type t. */\n");
    printf("static const int8_t heb_days_in_month_tab[%d][%d] PROGMEM = {\n",
           NUM_YEAR_TYPES, ADAR2 + 1);
    for (int t = 0; t < NUM_YEAR_TYPES; t++) {
        printf("  {");
        for (int m = 0; m <= ADAR2; m++) {
            printf("%d", days_in_month_tab[t][m]);
            if (m < ADAR2) printf(",");
        }
        printf("}");
        if (t < NUM_YEAR_TYPES - 1) printf(",");
        printf("\n");
    }
    printf("};\n\n");

    printf("/* month_offset_tab[t][m]: days from Tishrei 1 to 1st of month m. */\n");
    printf("static const int16_t heb_month_offset_tab[%d][%d] PROGMEM = {\n",
           NUM_YEAR_TYPES, ADAR2 + 2);
    for (int t = 0; t < NUM_YEAR_TYPES; t++) {
        printf("  {");
        for (int m = 0; m <= ADAR2 + 1; m++) {
            printf("%d", month_offset_tab[t][m]);
            if (m < ADAR2 + 1) printf(",");
        }
        printf("}");
        if (t < NUM_YEAR_TYPES - 1) printf(",");
        printf("\n");
    }
    printf("};\n\n");

    printf("/* month_by_day_of_year[t][d]: month containing d'th day (0-based) after Tishrei 1. */\n");
    printf("static const int8_t heb_month_by_day_of_year[%d][%d] PROGMEM = {\n",
           NUM_YEAR_TYPES, MAX_DAYS_IN_YEAR);
    for (int t = 0; t < NUM_YEAR_TYPES; t++) {
        printf("  {");
        for (int d = 0; d < MAX_DAYS_IN_YEAR; d++) {
            printf("%d", month_by_day_of_year[t][d]);
            if (d < MAX_DAYS_IN_YEAR - 1) {
                if ((d + 1) % 40 == 0) printf(",\n   ");
                else printf(",");
            }
        }
        printf("}");
        if (t < NUM_YEAR_TYPES - 1) printf(",");
        printf("\n");
    }
    printf("};\n\n");

    printf("#endif /* TABLES_DATA_H */\n");
    return 0;
}
