#!/usr/bin/env python3
"""
gen_locales.py - Extract Hebrew translations from the Go locales source
and generate a C locale data file (locale_data.h).

Reads strings_he.go and produces a sorted C array of {key, value} pairs.
"""
import re
import sys

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/opencode/hebcal-locales/strings_he.go"
    
    with open(src, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Match: Catalog.SetString(tag_he, "key", "value")
    # Keys and values can contain escaped quotes and Hebrew
    pattern = r'Catalog\.SetString\(tag_he,\s*"((?:[^"\\]|\\.)*)",\s*"((?:[^"\\]|\\.)*)"\)'
    matches = re.findall(pattern, content)
    
    # Unescape Go string escapes
    def unescape(s):
        s = s.replace('\\"', '"')
        s = s.replace('\\n', '\n')
        s = s.replace('\\t', '\t')
        s = s.replace('\\\\', '\\')
        return s
    
    entries = []
    for key, value in matches:
        key = unescape(key)
        value = unescape(value)
        if key:  # skip empty keys
            entries.append((key, value))
    
    # Sort by key for binary search
    entries.sort(key=lambda x: x[0])
    
    # Generate C output
    print("/* AUTO-GENERATED by tools/gen_locales.py - DO NOT EDIT. */")
    print("/* Hebrew locale translations extracted from hebcal/locales strings_he.go */")
    print("#ifndef LOCALE_DATA_H")
    print("#define LOCALE_DATA_H")
    print()
    print('#include "arduino_compat.h"')
    print()
    print(f"/* {len(entries)} Hebrew translations */")
    print("typedef struct {")
    print("    const char *key;")
    print("    const char *val;")
    print("} heb_locale_entry_t;")
    print()
    print(f"static const heb_locale_entry_t heb_he_entries[{len(entries)}] PROGMEM = {{")
    
    for key, value in entries:
        # Escape for C string literal
        c_key = key.replace('\\', '\\\\').replace('"', '\\"')
        c_val = value.replace('\\', '\\\\').replace('"', '\\"')
        # Replace newlines in values with space (for MEMO descriptions)
        c_val = c_val.replace('\n', ' ')
        print(f'    {{"{c_key}", "{c_val}"}},')
    
    print("};")
    print()
    print(f"#define HEB_HE_ENTRIES_COUNT {len(entries)}")
    print()
    print("#endif /* LOCALE_DATA_H */")

if __name__ == "__main__":
    main()
